workflows:
  ios-sim:
    name: JARVIS iOS Simulator
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter create --platforms=ios --project-name jarvis .
      - flutter pub get
      - flutter build ios --release --no-codesign --simulator
    artifacts:
      - build/ios/iphonesimulator/Runner.app

  ios-device:
    name: JARVIS iOS Cihaz (Imzali)
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter create --platforms=ios --project-name jarvis .
      - flutter pub get
      - flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - alimeteozyazici@gmail.com
