workflows:
  ios-build:
    name: JARVIS iOS Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter create --platforms=ios --project-name jarvis .
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      email:
        recipients:
          - alimeteozyazici@gmail.com
